name: CI + CD

on:
  workflow_dispatch:

jobs:
  # ----------------------
  # Build Job
  # ----------------------
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo "Building the application..."

  # ----------------------
  # Deploy to Development
  # ----------------------
  DeployDev:
    name: Deploy to Development
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Dev
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: echo "Deploying to Development environment..."

  # ----------------------
  # Deploy to QA
  # ----------------------
  DeployQA:
    name: Deploy to QA
    needs: [DeployDev]
    runs-on: ubuntu-latest
    environment:
      name: QA
      url: 'http://qa.myapp.com'
    steps:
      - name: Deploy
        run: echo "Deploying to QA environment..."
